name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      run: pip install -r requirements.txt

    - name: Run Test
      run: echo "Test Passed"